- cross-cloud.yml
> Promote K8s 1.10.4 and Linkerd 1.4.2 to cncf.ci

- cross-cloud.yml
VMware would like this to say VMware vSphere instead of VMware Cloud on AWS
- merge to staging
> Update display name for VMware vSphere

- cross-cloud.yml
VMware would like this to say VMware vSphere instead of VMware Cloud on AWS
- looks good on staging
- merge to cncf.ci
> Update display name to VMware vSphere on cncf.ci

- cross-cloud.yml
Update Linkerd 1.4.4
- builds work as expected on cidev
- merge and test on staging
> Enable Linkerd 1.4.4 on staging

- cross-cloud.yml
Project release updates: 
- CoreDNS v1.2.0
- Fluentd v1.2.3
- needs tested on staging
> Enable CoreDNS v1.2.0 and Fluentd v1.2.3 on staging

- cross-cloud.yml
Goal: to promote release updates to staging
- Enable K8s 1.11.2 
- Enable Linkerd v1.4.6
- Enable Fluentd 1.2.4
> Update K8s, Linkerd, Fluentd on staging

- cross-cloud.yml
Goal: to promote release updates to cncf.ci
Enable K8s 1.11.2
Enable Linkerd v1.4.6
Enable Fluentd 1.2.4
> Update K8s, Linkerd, Fluentd versions to cncf.ci

- cross-cloud.yml
- enable CoreDNS v1.2.3
- enable Envoy v1.8.0
- enable OCI
> promote CoreDNS and Envoy release updates to staging

- cross-cloud.yml
- update Prometheus release to v2.5.0
- update CoreDNS release to v1.2.6
- update  Fluentd release to v1.3.0
> promote Prometheus, CoreDNS, Fluentd updates to staging

- cross-cloud.yml
- update CoreDNS: v1.3.1
- update Kubernetes: v1.13.3
- update Prometheus: v2.7.1
- update Fluentd: v1.3.3
- update Linkerd: 1.6.1
All Project builds were successful on ci dev, 
Skipping dev for today (under construction), 
Promoting updated stable releases to staging for QA
> update stable releases on staging

- cross-cloud.yml
Manually update order of projects (based on maturity/alpha): 
* to be automated in https://github.com/crosscloudci/crosscloudci/issues/120
1 - Kubernetes - to be shown in Test Environment section at top of screen
2 - CoreDNS (Graduated)
3 - Envoy (Graduated)
4 - Prometheus (Graduated)
5 - Fluentd (Incubating)
6 - Linkerd (Incubating)
7 - ONAP (Linux Foundation)
> Update order of projects on staging

- cross-cloud.yml
- enable fluentd v1.4.1 on staging
- not promoting from master due to "development mode"
> update fluentd stable release on staging

- cross-cloud.yml
https://github.com/crosscloudci/ci-dashboard/issues/77
Changes made: 
logo_url: "https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/icon/color/kubernetes-icon-color.svg?sanitize=true"
> #77 replace K8s png logo with svg logo

- cross-cloud.yml
Promote release updates from integration to staging:
- enable CoreDNS v1.5.0
- enable Envoy v1.10.0
- enable Prometheus v2.8.1
- enable Fluentd v1.4.2
Skipping dev environment due to work in progress.
> update project releases on staging

- cross-cloud.yml
crosscloudci/crosscloudci#120
Temporarily changing line 177 on master
from cncf_relation: "Incubating"
to cncf_relation: "Graduated"
Will revert back after QA passes A/C
> QA sub-headers and relation on dev

- cross-cloud.yml
> enable CoreDNS v1.5.1 on cidev global

- cross-cloud.yml
QA Fluentd per-project release details on staging
Deleted line 149
> QA Fluentd release deleted line 149

- cross-cloud.yml
> enable CoreDNS v1.5.2 on cidev

- cross-cloud.yml
then Incubating sub-header should not be displayed
> QA if Linkerd is Graduated

- ADDAPROJECT.md
- cross-cloud.yml
Promote K8s v1.16.2 and use fluentd stable helm chart
issues:
- crosscloudci/crosscloudci#181
- vulk/cncf_ci#265
> Promote K8s v1.16.2 & fluentd chart fix to production

- cross-cloud.yml
1.  Adds vitess to cross-cloud.yml
2. Also addes etcd but it is currently disabled as the build is failing
Issues:
- https://github.com/crosscloudci/crosscloudci/issues/35
- https://github.com/vulk/cncf_ci/issues/302
> Promote vitess to production

- cross-cloud.yml
1. adjust ordering so that Graduated Projects are listed in alphabetical order
- TUF = 7
- Vitess = 8
Issues:
- maintenance
> Adjust ordering of TUF and Vitess (alphabetical)
