crosscloudci/cncf-configuration

- cross-cloud.yml
replace /master with /commit path
> update Linkerd logo

- cross-cloud.yml
- update prometheus stable_ref: "v2.0.0" to stable_ref: "v2.1.0"
- update linkerd  stable_ref: "1.3.3" to   "1.3.5"
> Update project releases on cross-cloud.yml

- cross-cloud.yml
update Kubernetes 1.8.1 to 1.9.3
> Update cross-cloud.yml for K8s 1.9.3

- cross-cloud.yml
Add option for setting the helm chart repo for ONAP
> Add option for setting the helm chart repo for ONAP

- cross-cloud.yml
- promote K8s 1.9.3 to staging
- promote Prometheus 2.1.0 to staging
- promote CoreDNS 1.0.6 to staging
- promote Linkerd 1.3.5 to staging
> Promote dev to staging

- cross-cloud.yml
*V1.2.0 Release:*
- ONAP integration 
- K8s 1.9.4
- Prometheus 2.2.1
- CoreDNS 1.1.0
> promote Integration to dev

- cross-cloud.yml
*V1.2.0 Release:*
- ONAP integration - new project
- K8s 1.9.4 - new K8s release
- Prometheus 2.2.1 - new release
- CoreDNS 1.1.0 - new release
> Promote Staging to Production

- cross-cloud.yml
testing OpenStack on staging.cncf.ci
> Promote "OpenStack true" to staging

- cross-cloud.yml
- update K8s to 1.9.6
- update Fluentd to 1.1.2
> promote K8s 1.9.6 and Fluentd 1.1.2 to dev

- cross-cloud.yml
> promote K8s from 1.10.0 to 1.9.6 on dev

- cross-cloud.yml
- update K8s to 1.10.0
- update fluentd to 1.1.3
- add Oracle cloud (false)
> update integration yml file with updates

- cross-cloud.yml
- update K8s to 1.10.0
- update fluentd to 1.1.3
- add Oracle cloud (false)
> promote fluentd, k8s and oracle to dev

- cross-cloud.yml
- update Linkerd 1.3.7 
- update Fluentd 1.1.3
> Promote Linkerd 1.3.7 & Fluentd 1.1.3 to dev environment

- cross-cloud.yml
- GKE = false
- update Linkerd 1.3.7
- update Fluentd 1.1.3
> promote linkerd, fluentd, GKE false to staging

- cross-cloud.yml
update K8s version from 1.9x to 1.10.1, released on 4/12/2018
> Add K8s 1.10.1 to dev

- cross-cloud.yml
update K8s to 1.10.3
update CoreDNS to v1.1.3
Update Linkerd to v1.4.1
Update Fluentd to v1.2.1
> Promoting Update K8s, CoreDNS, Fluentd, Linkerd versions to Production

- cross-cloud.yml
> Promote K8s and Linkerd to dev

- cross-cloud.yml
- K8s 1.10.5
- Prometheus 2.3.1
- CoreDNS 1.1.4
> Update K8s 1.10.5, Prometheus 2.3.1, CoreDNS 1.1.4 on staging

- cross-cloud.yml
- Prometheus 2.3.0
- Linkerd 1.4.3 
- Fluentd 1.2.2
> Update Prometheus 2.3.0, Linkerd 1.4.3 and Fluentd 1.2.2 on cncf.ci

- cross-cloud.yml
- change platform name from vSphere to VMware Cloud on AWS
> Promote K8s 1.11.0 and "VMware Cloud on AWS" display name to staging

- cross-cloud.yml
- Enable Linkerd 1.4.4
- Enable CoreDNS v1.2.0 
- Enable Fluentd v1.2.3
> Promote project updates to cncf.ci

- cross-cloud.yml
- update Prometheus to v2.3.2 
- update Linkerd to v1.4.5
- please merge and test on staging
> Enable Prometheus 2.3.2 and Linkerd 1.4.5 on staging

- cross-cloud.yml
- update Prometheus to v2.3.2 
- update Linkerd to v1.4.5
- looks good on staging
- merge to production
> Enable Prometheus 2.3.2 and Linkerd 1.4.5 to cncf.ci

- cross-cloud.yml
- update Kubernetes to v1.11.1
- merge and test on staging
> Enable K8s 1.11.1 to staging

- cross-cloud.yml
see https://github.com/crosscloudci/crosscloudci/issues/63
> remove IBM Cloud from staging

- cross-cloud.yml
- K8s v1.11.1
- looks good on staging
- please merge to cncf.ci
> Enable K8s 1.11.1 to cncf.ci

- cross-cloud.yml
- merge to staging
- test on staging
> Re-enable IBM Cloud on staging

- cross-cloud.yml
- looks good on staging
- merge to production
> Enable IBM Cloud to cncf.ci

- cross-cloud.yml
update project release names on dev
update provider display names on dev
> Update releases and provider names on dev 

- cross-cloud.yml
- Enable CoreDNS 1.2.2 
- Enable Envoy 1.7.1
> Enable CoreDNS 1.2.2 and Envoy 1.7.1 on staging

- cross-cloud.yml
- update K8s to v1.12.0
- update Prometheus to v2.4.3
- update Fluentd to v1.2.6
- update Linkerd to 1.5.0
> Promote K8s and project updates to staging

- cross-cloud.yml
> Promote K8s v1.12.1 to staging

- cross-cloud.yml
- Set cloud providers to false on staging environment
- Packet=true
- Prep for v2.0.0 release (clouds to be removed on Mon, Feb 25, 2019)
> Set cloud providers to false on staging

- cross-cloud.yml
> revert to K8s v1.13.0 for v2.0.0 release

- cross-cloud.yml
cncf-configuration yml file updates for v2.0.0 release include: 
- Set providers to false 
- Update stable releases for projects
- Manual re-ordering of projects based on maturity/alpha order
> promote updates for v2.0.0 release

- cross-cloud.yml
- enable CoreDNS v1.4.0 
- enable Prometheus v2.8.0 
- enable Fluentd v1.4.0
- enable Linkerd 1.6.2
> update project releases on dev

- cross-cloud.yml
- enable CoreDNS v1.4.0
- enable Prometheus v2.8.0
- enable Fluentd v1.4.0
- enable Linkerd 1.6.2
> update project releases on staging

- cross-cloud.yml
- enable CoreDNS v1.4.0
- enable Prometheus v2.8.0
- enable Fluentd v1.4.0
- enable Linkerd 1.6.2
> Update projects' stable releases on production

- cross-cloud.yml
> update fluentd stable release on cidev

- cross-cloud.yml
> update fluentd stable release on dev

- cross-cloud.yml
https://github.com/crosscloudci/crosscloudci/issues/102
Change where project details (display name, logo, caption) are retrieved for cncf.ci:
- add configuration_repo for all projects to production
- new project-configuration yml files have been QA'd and work as expected on staging
> #102 add configuration_repos for all projects to production

- cross-cloud.yml
> update fluentd stable release on cncf.ci 

- cross-cloud.yml
https://github.com/crosscloudci/ci-dashboard/issues/77
ONAP = true
> enable onap to test 77

- cross-cloud.yml
https://github.com/crosscloudci/ci-dashboard/issues/77
enable projects on cidev to test svg logos
> #77 enable projects to test svg logos

- cross-cloud.yml
- enable CoreDNS v1.5.0
- enable Envoy v1.10.0
- enable Prometheus v2.8.1
- enable Fluentd v1.4.2
> update project releases on ci dev

- cross-cloud.yml
Promote release updates from staging to production:
- enable CoreDNS v1.5.0
- enable Envoy v1.10.0
- enable Prometheus v2.8.1
- enable Fluentd v1.4.2
> update project releases on cncf.ci

- cross-cloud.yml
> update prometheus version on ci dev

- cross-cloud.yml
Changes made: 
fluentd: 
order: 4
prometheus: 
order: 5
> Re-order fluentd, graduated

- cross-cloud.yml
- enable prometheus v2.9.0 on staging
skip dev due to work in progress
> update prometheus version on staging

- cross-cloud.yml
> enable prometheus v2.9.1 on ci dev

- cross-cloud.yml
- enable prometheus v2.9.1
- passed on cidev
- skipping dev due to work in progress
> enable prometheus v2.9.1 on staging

- cross-cloud.yml
- move graduated fluentd to 4th place
- enable prometheus v2.9.1
- passed on staging
> enable prometheus v2.9.1, reorder fluentd on cncf.ci

- cross-cloud.yml
Pull request https://github.com/crosscloudci/ci_status_repository/pull/18 depends on this ticket
> Add support for separate environments for status results - K8s drop-down selection

- cross-cloud.yml
> enable Prometheus v2.9.2 on ci dev

- cross-cloud.yml
> enable Prometheus v2.9.2 on dev 

- cross-cloud.yml
> enable Prometheus v2.9.2 on staging

- cross-cloud.yml
> enable Prometheus v2.9.2 on cncf.ci

- cross-cloud.yml
> enable Linkerd 1.6.3 on ci dev

- cross-cloud.yml
https://github.com/vulk/cncf_ci/issues/143
Enables flags for 143
> #143 coredns / arm

- cross-cloud.yml
Coredns Arm
https://github.com/crosscloudci/crosscloudci#133
https://github.com/vulk/cncf_ci/issues/143
> #133 CoreDNS

- cross-cloud.yml
[Feature] Add Arm support to CNCF Graduated project: Prometheus #142 https://github.com/vulk/cncf_ci/issues/142
https://github.com/crosscloudci/crosscloudci/issues/135
[Feature] Add Arm support to CNCF Graduated project: Fluentd #145 https://github.com/vulk/cncf_ci/issues/145
https://github.com/crosscloudci/crosscloudci/issues/136
[Feature] Add Arm support to CNCF Graduated project: Envoy #144 https://github.com/vulk/cncf_ci/issues/144
https://github.com/crosscloudci/crosscloudci/issues/134
> Arm support for graduated projects

- cross-cloud.yml
enable Prometheus v2.10.0
enable Fluentd v1.5.0
> enable latest releases for Prometheus & Fluentd

- cross-cloud.yml
- enable Prometheus v2.10.0
- enable Fluentd v1.5.0
>  enable latest releases for Prometheus & Fluentd on dev

- cross-cloud.yml
> enable Fluentd 1.5.1 on ci dev

- cross-cloud.yml
>  enable Fluentd 1.5.1 on dev

- cross-cloud.yml
> enable Fluentd 1.5.1 on staging

- cross-cloud.yml
> enable fluentd v1.5.2 on ci dev

- cross-cloud.yml
>  enable fluentd v1.5.2 on staging

- cross-cloud.yml
https://github.com/crosscloudci/crosscloudci/issues/103
step 1. Add a '#' to the start of any line which has stable_ref for each project,
step 2. update stable_ref for each project, https://github.com/crosscloudci/fluentd-configuration
> QA fluentd stable_ref on staging

- cross-cloud.yml
> enable Linkerd 1.6.4 on cidev

- cross-cloud.yml
> enable Fluentd v1.6.0 on cidev

- cross-cloud.yml
ticket 60 - testing that sub-headers have correct functionality
> updating cncf_relation for linkerd

- cross-cloud.yml
crosscloudci/crosscloudci#103 Stable/Release Ref
> crosscloudci/crosscloudci#103 Stable/Release Ref 

- cross-cloud.yml
> enable CoreDNS v1.5.2

- cross-cloud.yml
>  vulk/cncf_ci#150

- cross-cloud.yml
added CNCF to Graduated and Incubating cncf_relations so that the front would pass QA
> updating cncf_relation for frontend app

- cross-cloud.yml
https://github.com/crosscloudci/cncf-configuration/pull/141/files
> Reverting PR 141 on dev

- cross-cloud.yml
QA sub-headers on staging, assigning label of Incubating to Linkerd
- https://github.com/crosscloudci/crosscloudci/issues/120
> Linkerd is Incubating, end of QA

- cross-cloud.yml
Promote sub-headers and sorting to production
Promote supporting different cncf.ci environments for each project configuration
- LGTM on staging
- crosscloudci/crosscloudci#120
- crosscloudci/crosscloudci#159
> Promote Sub-headers and syncing environments to production

- cross-cloud.yml
add new project to global config cncf-configuration cross-cloud.yml on master branch
https://github.com/crosscloudci/crosscloudci/issues/172
> add linkerd2 to global config, false during dev

- ADDAPROJECT.md
- cross-cloud.yml
>  Initial CI Proxy with end point

- ADDAPROJECT.md
- cross-cloud.yml
crosscloudci/crosscloudci#176 vulk/cncf_ci/issues/250
> Travis ci (linkerd2)

- cross-cloud.yml
> Disable testproj on prod

- cross-cloud.yml
set testproj to false on staging
> set testproj to false on staging

- cross-cloud.yml
Promote K8s v1.6.2 & fluentd chart fix
> Promote K8s v1.6.2 & fluentd chart fix

- cross-cloud.yml
> Integration - Jaeger

- ADDAPROJECT.md
- cross-cloud.yml
Add Jaeger to the dashboard
issues:
- crosscloudci/crosscloudci#185
- vulk/cncf_ci/issues/281
* [] cidev.cncf.ci
* []  Bug fix (non-breaking change which fixes an issue)
> Add Jaeger to the dashboard

- cross-cloud.yml
1. Enables Jaeger on the cncf.ci dashboard.
Issues:
- vulk/cncf_ci/issues/295
- vulk/cncf_ci/issues/281
> Enable Jaeger on the cncf.ci dashboard(Production)

- cross-cloud.yml
1. enables etcd
Issues:
- crosscloudci/crosscloudci#209
> Reenable etcd in staging.

- cross-cloud.yml
1. enables etcd
Issues:
- crosscloudci/crosscloudci#209
> Etcd to production
